### ISSUE TITLE
Error in upload

### ISSUE THREAD

**Issue by fredpook** [zotonic/mod_admin_multiupload#2]
Maybe not compatible with zotonic 0.13.x anymore?

Error is:

16:08:32.122 [info] identify of '/tmp/ztmp-zotonic001@ginger-7631173.38675258[0]' failed:
identify: unable to open image `/tmp/ztmp-zotonic001@ginger-7631173.38675258': No such file or directory @ error/blob.c/OpenBlob/2709.
identify: no decode delegate for this image format`38675258' @ error/constitute.c/ReadImage/501.

16:08:32.128 [error] Error '{badmatch,{error,enoent}}' for transport message {z_msg_v1,1,false,<<"DBlBkrebuTwiC9Bq47g3-z-4">>,1456758540169,ubf,postback,undefined,desktop,undefined,<<"DBlBkrebuTwiC9Bq47g3">>,{postback_event,<<"S40XMa0Pq7xvgpBdyYzzVDWv4zWDaAVkAAVjbGlja2sABm9ra21xa2sABm9ra21xa2gCZAAKc2F2ZV9iYXRjaGwAAAABaAJkAAJpZGQACXVuZGVmaW5lZGpkABVtb2RfYWRtaW5fbXVsdGl1cGxvYWQ">>,<<"okkmqk">>,undefined,<<>>,{q,[]}}}
16:08:32.128 [error] Stack: [{z_media_archive,archive_copy_opt,3,[{file,"src/support/z_media_archive.erl"},{line,126}]},{m_media,replace_file_db,5,[{file,"src/models/m_media.erl"},{line,534}]},{mod_admin_multiupload,'-save_batch/2-fun-0-',2,[{file,"/vagrant/modules/mod_admin_multiupload/mod_admin_multiupload.erl"},{line,84}]},{lists,map,2,[{file,"lists.erl"},{line,1237}]},{mod_admin_multiupload,save_batch,2,[{file,"/vagrant/modules/mod_admin_multiupload/mod_admin_multiupload.erl"},{line,82}]},{z_transport,incoming_with_session,2,[{file,"src/support/z_transport.erl"},{line,256}]},{z_transport,incoming_msgs,2,[{file,"src/support/z_transport.erl"},{line,193}]},{z_transport,incoming,2,[{file,"src/support/z_transport.erl"},{line,161}]}]

**Comment by mworrell** [comment]
Seems like imagemagick doesn't understand your file. At least that means the "no decode delegate".  Try running identify on your file from the command line.

**Comment by fredpook** [comment]
Imagemagick is all ok.

@arjan Are the temporary files deleted automatically just after upload, so the "upload" step is too late?

**Comment by mworrell** [comment]
Turns out that there is indeed a problem with this module and how temporary files are managed.
We need to redo this module.
